services:
  # 1. The gRPC Application
  grpc-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grpc-demo-service
    ports:
      - "9090:9090" # gRPC Port
      - "8080:8080" # Management/Actuator Port
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/demo_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=pass
      - SPRING_THREADS_VIRTUAL_ENABLED=true
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - grpc-net

  # 2. The Database (Postgres)
  postgres-db:
    image: postgres:17-alpine
    container_name: postgres-db
    environment:
      - POSTGRES_DB=demo_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d demo_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - grpc-net

  # 3. Observability (Prometheus) - Essential for gRPC performance
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./infra/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    networks:
      - grpc-net

networks:
  grpc-net:
    driver: bridge